version: '3.8'

services:
  present-or-panic:
    image: ghcr.io/raphaelbleier/powerpoint_karaoke:latest
    container_name: present_or_panic
    ports:
      - "8080:8080"
    environment:
      # Hier trägst du deine echte ID und den API Key ein:
      - PORT=8080
      - POWERPOINTS_FOLDER_ID=1aBcDeFgH-...
      - GOOGLE_API_KEY=AIzaSy...
      
      # Diese beiden kannst du komplett löschen, wenn du den API-Key benutzt:
      # - GOOGLE_SERVICE_ACCOUNT_EMAIL=
      # - GOOGLE_PRIVATE_KEY=
    restart: unless-stopped
